---
-
  name: Update & installs updates
  hosts: all
  become: true

  tasks:
    - name: Upgrade all packages to the latest version and also removing garbage 
      shell: sudo apt update  && sleep 5s && sudo apt upgrade -y && sleep 5s && sudo apt autoclean -y && sleep 5s && sudo apt autoremove -y && sleep 5s && sudo flatpak update -y
    - name: Backing up data
      ansible.builtin.include_tasks: ./tasks/backup.yaml
    # mandatory rebootonly enable this  if you want to system to reboot.
    #    - name: Rebooting Machine
    #      shell: sudo reboot
