---
version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=United States/New York
      - CLI_ARGS= #optional
    volumes:
      - local/path/to/mount/:/config
      - local/path/to/mount/:/backups
      - local/path/to/mount/:/source
    ports:
      - 8200:8200
    restart: unless-stopped
