apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: helixx-cloud-hpa
  namespace: helixx-cloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextcloud
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 8  # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Target 70% CPU utilization
