---
-
  name: Update
  hosts: all
  become: true

  tasks:
    - name: Upgrade all packages to the latest version and also remove garbage
      shell: sudo apt update  && sleep 5s && sudo apt upgrade -y && sleep 5s && sudo apt autoclean -y && sleep 5s && sudo apt autoremove -y
    - name: performing container backup
      shell: /usr/sbin/containers_backup # This script has to exist on remote machine in order to work. 

    # mandatory reboot only enable this  if you want to system to reboot.
    - name: Rebooting Machine
      shell: sudo reboot
