---
-

# This playbook is to update RHEL distro using dnf package manager

  name:  Perform system update and cleanup
  hosts: all
  become: yes
  ignore_errors: yes
  
  tasks:
  - name:  Perform system update and cleanup
    shell: sudo dnf update -y && sudo  dnf upgrade -y && sudo dnf autoremove && sudo  dnf clean all && brew update && brew upgrade
  - name: Backing up data
    ansible.builtin.include_tasks: ./tasks/backup.yaml
  # - name:  Reboot server 
  #   command: sudo reboot 