#!/bin/bash

set -o errexit

# User-configurable variables
BASE_PATH="/path/to/your/base_directory"
LOGFILE="${BASE_PATH}/path/to/your/logfile.log"
JUMPBOX_PLAYBOOK_DIR="${BASE_PATH}/path/to/jumpbox/playbook/directory"
MEDIA_SERVER_PLAYBOOK_DIR="${BASE_PATH}/path/to/media/server/playbook/directory"
LAB_VM_PLAYBOOK_DIR="${BASE_PATH}/path/to/lab/vm/playbook/directory"
RSYNC_DESTINATION="user@hostname:/path/to/backup/location"

# Begin script execution
echo "Starting playbook run script at $(date)" | tee -a $LOGFILE
echo "----------------------------------------" | tee -a $LOGFILE

cd $BASE_PATH

echo 'JumpboxVM maintenance started...' | tee -a $LOGFILE
cd $JUMPBOX_PLAYBOOK_DIR && ./run_playbook.sh &>> $LOGFILE

echo 'JumpboxVM maintenance completed moving on....' | tee -a $LOGFILE
sleep 2s

echo 'Performing maintenance on Media Server...' | tee -a $LOGFILE
cd $MEDIA_SERVER_PLAYBOOK_DIR
./run_playbook.sh &>> $LOGFILE

echo 'Performing maintenance on LabVM...' | tee -a $LOGFILE
cd $LAB_VM_PLAYBOOK_DIR
./run_playbook.sh &>> $LOGFILE

sleep 3s

echo 'Backing up infra code....' | tee -a $LOGFILE
rsync -ravx ${BASE_PATH}/path/to/infra/playbooks/ $RSYNC_DESTINATION &>> $LOGFILE

echo "----------------------------------------" | tee -a $LOGFILE
echo "System update was done today on $(date)" | tee -a $LOGFILE
